server:
  port: ${PORT:8080}

spring:
  application:
    name: phimium-be

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
   secret-key: ${TOKEN_SECRET_KEY}
   expiration: 86400000
   refresh-expiration: 604800000

  jackson:
    time-zone: Asia/Ho_Chi_Minh
  sepay:
    merchant-id: ${SEPAY_MERCHANT_ID}
    secret-key:  ${SEPAY_SECRET_KEY}
    checkout-url: ${SEPAY_CHECKOUT_URL:https://pay-sandbox.sepay.vn/v1/checkout/init}
    api-url: ${SEPAY_API_URL:https://pgapi-sandbox.sepay.vn}
    success-url: ${SEPAY_SUCCESS_URL}
    error-url: ${SEPAY_ERROR_URL}
    cancel-url: ${SEPAY_CANCEL_URL}



